package br.edu.dmos5.projeto_joao_santos_dmos5.util;

import java.util.Arrays;
import java.util.List;

import br.edu.dmos5.projeto_joao_santos_dmos5.model.Traducao;

public class MoedaTraducaoUtil {

    public static List<Traducao> traducoes = Arrays.asList(
            new Traducao("AED", "United Arab Emirates Dirham", "Emirados Árabes Unidos Dirham"),
            new Traducao("AFN", "Afghan Afghani", "Afegão afegão"),
            new Traducao("ALL", "Albanian Lek", "Lek Albanês"),
            new Traducao("AMD", "Armenian Dram", "Dram Armênio"),
            new Traducao("ANG", "Netherlands Antillean Guilder","Florim das Antilhas Holandesas"),
            new Traducao("AOA", "Angolan Kwanza","Kwanza Angolano"),
            new Traducao("ARS", "Argentine Peso","Peso Argentino"),
            new Traducao("AUD", "Australian Dollar","Dólar Australiano"),
            new Traducao("AWG", "Aruban Florin","Aruban Florin"),
            new Traducao("AZN", "Azerbaijani Manat","Manat do Azerbaijão"),
            new Traducao("BAM", "Bosnia-Herzegovina Convertible Mark","Marco Conversível da Bósnia-Herzegovina"),
            new Traducao("BBD", "Barbadian Dollar","Dólar Barbadense"),
            new Traducao("BCH", "Bitcoin Cash","Bitcoin Cash"),
            new Traducao("BDT", "Bangladeshi Taka","Taka de Bangladesh"),
            new Traducao("BGN", "Bulgarian Lev","Lev Búlgaro"),
            new Traducao("BHD", "Bahraini Dinar","Dinar do Bahrein"),
            new Traducao("BIF", "Burundian Franc","Franco do Burundi"),
            new Traducao("BMD", "Bermudan Dollar","Dólar Bermudense"),
            new Traducao("BND", "Brunei Dollar","Dólar de Brunei"),
            new Traducao("BOB", "Bolivian Boliviano","Boliviano Boliviano"),
            new Traducao("BRL", "Brazilian Real","Real Brasileiro"),
            new Traducao("BSD", "Bahamian Dollar","Dólar das Bahamas"),
            new Traducao("BTC", "Bitcoin","Bitcoin"),
            new Traducao("BTG", "Bitcoin Gold","Bitcoin Gold"),
            new Traducao("BWP", "Botswanan Pula","Botswana Pula"),
            new Traducao("BZD", "Belize Dollar","Dólar de Belize"),
            new Traducao("CAD", "Canadian Dollar","Dólar Canadense"),
            new Traducao("CDF", "Congolese Franc","Franco Congolês"),
            new Traducao("CHF", "Swiss Franc","Franco Suíço"),
            new Traducao("CLP", "Chilean Peso","Peso Chileno"),
            new Traducao("CNH", "Chinese Yuan (offshore)","Yuan Chinês (offshore)"),
            new Traducao("CNY", "Chinese Yuan","Yuan Chinês"),
            new Traducao("COP", "Colombian Peso","Peso Colombiano"),
            new Traducao("CRC", "Costa Rican Colón","Colón da Costa Rica"),
            new Traducao("CUC", "Cuban Convertible Peso","Peso Cubano Conversível"),
            new Traducao("CUP", "Cuban Peso","Peso Cubano"),
            new Traducao("CVE", "Cape Verdean Escudo","Escudo Cabo-Verdiano"),
            new Traducao("CZK", "Czech Republic Koruna","Coroa da República Tcheca"),
            new Traducao("DASH", "DASH", "TRAÇO"),
            new Traducao("DJF","Djiboutian Franc","Franco do Djibuti"),
            new Traducao("DKK","Danish Krone","Coroa Dinamarquesa"),
            new Traducao("DOP","Dominican Peso","Peso Dominicano"),
            new Traducao("DZD","Algerian Dinar","Dinar argelino"),
            new Traducao("EGP","Egyptian Pound","Libra egípcia"),
            new Traducao("EOS","EOS","EOS"),
            new Traducao("ETB","Ethiopian Birr","Birr etíope"),
            new Traducao("ETH","Ethereum","Ethereum"),
            new Traducao("EUR","Euro","Euro"),
            new Traducao("FJD","Fijian Dollar","Dólar Fijiano"),
            new Traducao("GBP","British Pound Sterling","Libra Esterlina Britânica"),
            new Traducao("GEL","Georgian Lari","Lari Georgiano"),
            new Traducao("GHS","Ghanaian Cedi","Cedi de Gana"),
            new Traducao("GIP","Gibraltar Pound","Libra de Gibraltar"),
            new Traducao("GMD","Gambian Dalasi","Gâmbia Dalasi"),
            new Traducao("GNF","Guinean Franc","Franco Guineense"),
            new Traducao("GTQ","Guatemalan Quetzal","Quetzal da Guatemala"),
            new Traducao("GYD","Guyanaese Dollar","Dólar Guianense"),
            new Traducao("HKD","Hong Kong Dollar","Dólar de Hong Kong"),
            new Traducao("HNL","Honduran Lempira","Lempira Hondurenha"),
            new Traducao("HRK","Croatian Kuna","Kuna Croata"),
            new Traducao("HTG","Haitian Gourde","Gourde Haitiana"),
            new Traducao("HUF","Hungarian Forint","Forint Húngaro"),
            new Traducao("IDR","Indonesian Rupiah","Rúpia da Indonésia"),
            new Traducao("ILS","Israeli New Sheqel","Novo Shekel Israelita"),
            new Traducao("INR","Indian Rupee","Rupia Indiana"),
            new Traducao("IQD","Iraqi Dinar","Dinar Iraquiano"),
            new Traducao("IRR","Iranian Rial","Rial Iraniano"),
            new Traducao("ISK","Icelandic Króna","Króna Islandês"),
            new Traducao("JMD","Jamaican Dollar","Dólar Jamaicano"),
            new Traducao("JOD","Jordanian Dinar","Dinar Jordaniano"),
            new Traducao("JPY","Japanese Yen","Yen Japonês"),
            new Traducao("KES","Kenyan Shilling","Xelim Queniano"),
            new Traducao("KGS","Kyrgystani Som","Som do Quirguistão"),
            new Traducao("KHR","Cambodian Riel","Riel Cambojano"),
            new Traducao("KMF","Comorian Franc","Franco das Comores"),
            new Traducao("KRW","South Korean Won","Won sul-coreano"),
            new Traducao("KWD","Kuwaiti Dinar","Dinar do Kuwait"),
            new Traducao("KYD","Cayman Islands Dollar","Dólar das Ilhas Cayman"),
            new Traducao("KZT","Kazakhstani Tenge","Tenge do Cazaquistão"),
            new Traducao("LAK","Laotian Kip","Kip do Laos"),
            new Traducao("LBP","Lebanese Pound","Libra Libanesa"),
            new Traducao("LKR","Sri Lankan Rupee","Rúpia do Sri Lanka"),
            new Traducao("LRD","Liberian Dollar","Dólar Liberiano"),
            new Traducao("LSL","Lesotho Loti","Lesotho Loti"),
            new Traducao("LTC","Litecoin","Litecoin"),
            new Traducao("LYD","Libyan Dinar","Dinar da Líbia"),
            new Traducao("MAD","Moroccan Dirham","Dirham Marroquino"),
            new Traducao("MDL","Moldovan Leu","Leu da Moldávia"),
            new Traducao("MKD","Macedonian Denar","Denar Macedônio"),
            new Traducao("MMK","Myanma Kyat","Myanma Kyat"),
            new Traducao("MOP","Macanese Pataca","Pataca Macaense"),
            new Traducao("MUR","Mauritian Rupee","Rúpia da Maurícia"),
            new Traducao("MVR","Maldivian Rufiyaa","Rufiyaa das Maldivas"),
            new Traducao("MWK","Malawian Kwacha","Kwacha do Malawi"),
            new Traducao("MXN","Mexican Peso","Peso Mexicano"),
            new Traducao("MYR","Malaysian Ringgit","Ringgit da Malásia"),
            new Traducao("MZN","Mozambican Metical","Metical Moçambicano"),
            new Traducao("NAD","Namibian Dollar","Dólar Namibiano"),
            new Traducao("NGN","Nigerian Naira","Naira Nigeriana"),
            new Traducao("NIO","Nicaraguan Córdoba","Córdoba Nicaraguense"),
            new Traducao("NOK","Norwegian Krone","Coroa Norueguesa"),
            new Traducao("NPR","Nepalese Rupee","Rúpia do Nepal"),
            new Traducao("NZD","New Zealand Dollar","Dólar neozelandês"),
            new Traducao("OMR","Omani Rial","Rial de Omã"),
            new Traducao("PAB","Panamanian Balboa","Balboa panamenho"),
            new Traducao("PEN","Peruvian Nuevo Sol","Nuevo Sol peruano"),
            new Traducao("PGK","Papua New Guinean Kina","Papua Nova Guiné Kina"),
            new Traducao("PHP","Philippine Peso","Peso filipino"),
            new Traducao("PKR","Pakistani Rupee","Rúpia do Paquistão"),
            new Traducao("PLN","Polish Zloty","Zloty polonês"),
            new Traducao("PYG","Paraguayan Guarani","Guarani Paraguaio"),
            new Traducao("QAR","Qatari Rial","Rial Catariano"),
            new Traducao("RON","Romanian Leu","Leu romeno"),
            new Traducao("RSD","Serbian Dinar","Dinar sérvio"),
            new Traducao("RUB","Russian Ruble","rublo russo"),
            new Traducao("RWF","Rwandan Franc","Franco ruandês"),
            new Traducao("SAR","Saudi Riyal","Rial saudita"),
            new Traducao("SBD","Solomon Islands Dollar","Dólar das Ilhas Salomão"),
            new Traducao("SCR","Seychellois Rupee","Rúpia das Seichelenses"),
            new Traducao("SDG","Sudanese Pound","Libra Sudanesa"),
            new Traducao("SEK","Swedish Krona","Coroa sueca"),
            new Traducao("SGD","Singapore Dollar","Dólar de Singapura"),
            new Traducao("SLL","Sierra Leonean Leone","Leoa Serra Leoa"),
            new Traducao("SOS","Somali Shilling","Xelim da Somália"),
            new Traducao("SRD","Surinamese Dollar","Dólar do Suriname"),
            new Traducao("SVC","Salvadoran Colón","Colón salvadorenho"),
            new Traducao("SZL","Swazi Lilangeni","Swazi Lilangeni"),
            new Traducao("THB","Thai Baht","Baht tailandês"),
            new Traducao("TJS","Tajikistani Somoni","Somoni do Tajiquistão"),
            new Traducao("TMT","Turkmenistani Manat","Manat do Turcomenistão"),
            new Traducao("TND","Tunisian Dinar","Dinar Tunisino"),
            new Traducao("TOP","Tongan Paʻanga","Pa'anga de Tonga"),
            new Traducao("TRY","Turkish Lira","Lira Turca"),
            new Traducao("TTD","Trinidad and Tobago Dollar","Dólar de Trinidad e Tobago"),
            new Traducao("TWD","New Taiwan Dollar","Novo dólar taiwanês"),
            new Traducao("TZS","Tanzanian Shilling","Xelim da Tanzânia"),
            new Traducao("UAH","Ukrainian Hryvnia","Hryvnia ucraniana"),
            new Traducao("UGX","Ugandan Shilling","Xelim de Uganda"),
            new Traducao("USD","United States Dollar","Dolar dos Estados Unidos"),
            new Traducao("UYU","Uruguayan Peso","Peso Uruguaio"),
            new Traducao("UZS","Uzbekistan Som","Som do Uzbequistão"),
            new Traducao("VND","Vietnamese Dong","Dong vietnamita"),
            new Traducao("XAF","CFA Franc BEAC","Franco CFA BEAC"),
            new Traducao("XAG","Silver (troy ounce)","Prata (onça troy)"),
            new Traducao("XAU","Gold (troy ounce)","Ouro (onça troy)"),
            new Traducao("XCD","East Caribbean Dollar","Dólar do Caribe Oriental"),
            new Traducao("XLM","Stellar Lumens","Lúmens Estelares"),
            new Traducao("XOF","CFA Franc BCEAO","Franco CFA BCEAO"),
            new Traducao("XRP","Ripple","Ondulação"),
            new Traducao("YER","Yemeni Rial","Rial iemenita"),
            new Traducao("ZAR","South African Rand","Rand sul-africano"),
            new Traducao("ZMW","Zambian Kwacha","Kwacha zambiano")
    );

    public static Traducao getValorTraducaoPorChave(String chave){
        Traducao traducao = null;
        for (int i = 0; i < traducoes.size(); i++){
            if(traducoes.get(i).getChave().equals(chave)){
                traducao = traducoes.get(i);
            }
        }
        return traducao;
    }
}
